import { Project } from "ts-morph";
const project = new Project();
let output = "";
output +=
    `/* The file is generated by generate-union.ts. DO NOT EDIT MANUALLY! */

import type * as serverToWeb from "../ws/server-to-web"
import type * as webToServer from "../ws/web-to-server"
import type * as serverToOc from "../ws/server-to-oc"
import type * as ocToServer from "../ws/oc-to-server"
import type * as general from "../ws/general"

`;
const source1 = project.addSourceFileAtPath("./ws/server-to-web.ts");
const exportedTypeAliases1 = source1.getTypeAliases().filter(typeAlias => typeAlias.isExported());
const unionType1 = exportedTypeAliases1.map(t => `serverToWeb.${t.getName()}`).join("\n    | ");
output += `export type ServerToWeb = \n    | ${unionType1}\n\n`;
const source2 = project.addSourceFileAtPath("./ws/web-to-server.ts");
const exportedTypeAliases2 = source2.getTypeAliases().filter(typeAlias => typeAlias.isExported());
const unionType2 = exportedTypeAliases2.map(t => `webToServer.${t.getName()}`).join("\n    | ");
output += `export type WebToServer = \n    | ${unionType2}\n\n`;
const source3 = project.addSourceFileAtPath("./ws/server-to-oc.ts");
const exportedTypeAliases3 = source3.getTypeAliases().filter(typeAlias => typeAlias.isExported());
const unionType3 = exportedTypeAliases3.map(t => `serverToOc.${t.getName()}`).join("\n    | ");
output += `export type ServerToOc = \n    | ${unionType3}\n\n`;
const source4 = project.addSourceFileAtPath("./ws/oc-to-server.ts");
const exportedTypeAliases4 = source4.getTypeAliases().filter(typeAlias => typeAlias.isExported());
const unionType4 = exportedTypeAliases4.map(t => `ocToServer.${t.getName()}`).join("\n    | ");
output += `export type OcToServer = \n    | ${unionType4}\n\n`;
const source5 = project.addSourceFileAtPath("./ws/general.ts");
const exportedTypeAliases5 = source5.getTypeAliases().filter(typeAlias => typeAlias.isExported());
const unionType5 = exportedTypeAliases5.map(t => `general.${t.getName()}`).join("\n    | ");
output += `export type General = \n    | ${unionType5}\n\n`;
output +=
    `export type All =
    | ServerToWeb
    | WebToServer
    | ServerToOc
    | OcToServer
    | General
`;
console.log(output);
const outputSource = project.createSourceFile("./utils/union.ts", output, { overwrite: true });
outputSource.saveSync();
