/* The file is generated by generate-union.ts. DO NOT EDIT MANUALLY! */

import type * as serverToWeb from "../ws/server-to-web.types"
import type * as webToServer from "../ws/web-to-server.types"
import type * as serverToOc from "../ws/server-to-oc.types"
import type * as ocToServer from "../ws/oc-to-server.types"

export type ServerToWeb = 
    | serverToWeb.AuthResponse
    | serverToWeb.DataCommonSet
    | serverToWeb.DataBotSet
    | serverToWeb.DataAeSet
    | serverToWeb.DataMcServerStatusSet
    | serverToWeb.AeOrderResult

export type WebToServer = 
    | webToServer.AuthRequest
    | webToServer.OcTaskRunSingle
    | webToServer.OcTaskAdd
    | webToServer.OcTaskRemove
    | webToServer.DataEventSet
    | webToServer.OcForward
    | webToServer.AeOrder

export type ServerToOc = 
    | serverToOc.AuthResponse
    | serverToOc.Task

export type OcToServer = 
    | ocToServer.AuthRequest
    | ocToServer.DataCommonSet
    | ocToServer.DataAeItemList
    | ocToServer.DataAeCpuList
    | ocToServer.DataEventAdd
    | ocToServer.DataEventSet
    | ocToServer.DataBotComponent
    | ocToServer.AeOrderResult
    | ocToServer.Log

export type All =
    | ServerToWeb
    | WebToServer
    | ServerToOc
    | OcToServer
